# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kudos', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-pub_date', 'mod_date'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=35)),
            ],
        ),
    ]
