# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('kudos', models.IntegerField()),
                ('draft', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='image/')),
                ('tags', models.TextField()),
            ],
        ),
    ]
